Repository skodaconnect/homeassistant-myskoda, pull requests merged in 2024-12, with the labels that each got.

#368 Improve auxiliary heater to show up on all supported vehicles
  custom_components/myskoda/climate.py
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/entity.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/number.py
  custom_components/myskoda/translations/en.json
Labels: bugfix

#386 Bump myskoda to 0.14.0
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#388 Add Outside temperature sensor entity
  custom_components/myskoda/icons.json
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#390 Disable MQTT connection during password check
  custom_components/myskoda/config_flow.py
Labels: bugfix

#387 AuxiliaryHeater entity updated
  custom_components/myskoda/climate.py
  custom_components/myskoda/coordinator.py
Labels: bugfix

#399 show HVACMode.FAN_ONLY also for AUXILIARY_HEATING_BASIC
  custom_components/myskoda/climate.py
Labels: bugfix

#401 Fix OutsideTemperature sensor setup
  custom_components/myskoda/sensor.py
Labels: bugfix

#408 Bump myskoda to 0.14.2
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#407 update outsideTemperature sensor
  custom_components/myskoda/sensor.py
Labels: bugfix

#413 Add links to shields
  README.md
Labels: documentation

#415 add download diagnostics feature
  README.md
  custom_components/myskoda/diagnostics.py
Labels: enhancement

#410 Prevent integration from stalling when MQTT does not connect
  custom_components/myskoda/__init__.py
  custom_components/myskoda/coordinator.py
Labels: bug

#424 Add sane limits to outside temperature
  custom_components/myskoda/const.py
  custom_components/myskoda/sensor.py
Labels: bugfix

#430 Bump myskoda to 0.15.0
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#431 CitigoE iV partial update
  custom_components/myskoda/coordinator.py
Labels: bugfix

#425 Improve incomplete response handling
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/error_handlers.py
Labels: bugfix

#433 Fix NoneType in initial startup
  custom_components/myskoda/coordinator.py
Labels: bugfix

#441 Bump myskoda to 0.15.1
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#445 Bump myskoda to 0.15.2
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#451 Bump myskoda to 0.15.4
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#452 add binary state sensor for each window and door (open/closed)
  README.md
  custom_components/myskoda/binary_sensor.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/translations/en.json
Labels: enhancement

#453 Handle marketing consent error in integration
  custom_components/myskoda/__init__.py
  custom_components/myskoda/translations/en.json
Labels: bugfix

#456 fix missing main render
  custom_components/myskoda/device_tracker.py
  custom_components/myskoda/image.py
Labels: bugfix

#462 Introduce fallback for mileage sensor
  custom_components/myskoda/sensor.py
Labels: bugfix

#463 fix for fix missing main render
  custom_components/myskoda/device_tracker.py
  custom_components/myskoda/image.py
Labels: bugfix

#466 Add AdBlue range sensor
  custom_components/myskoda/icons.json
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#467 add Gas Range and Gas Level sensors
  custom_components/myskoda/icons.json
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#437 Add Image entities for vehicle status
  custom_components/myskoda/image.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#482 Revert releaser
  .github/workflows/release.yml
Labels: dependencies

#478 Document adding a vehicle
  README.md
Labels: documentation

#490 Doc: template sensor for vehicle_in_motion
  README.md
Labels: documentation

#500 add generate diagnostics feature for the config entry section
  custom_components/myskoda/diagnostics.py
Labels: bugfix

#491 remove AuxiliaryHeating from partial update for CitigoE IV
  custom_components/myskoda/coordinator.py
Labels: bugfix

#498 Add Departure Timer 1,2,3 switch
  README.md
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/switch.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#499 Added romanian translation
  custom_components/myskoda/translations/ro.json
Labels: translations

#503 add "Unlock Plug when Charged" switch
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/switch.py
  custom_components/myskoda/translations/en.json
Labels: enhancement
