Repository skodaconnect/homeassistant-myskoda, pull requests merged in 2024-11, with the labels that each got.

#168 Activate Inspection Interval
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#223 Only show software version for MEB vehicles
  custom_components/myskoda/sensor.py
Labels: bugfix

#261 Trigger proper exceptions inside HA when an update fails
  custom_components/myskoda/coordinator.py
Labels: bugfix

#262 Rename lights to parkinglights
  custom_components/myskoda/binary_sensor.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/translations/en.json
Labels: bugfix

#264 Oil Inspection Sensor
  custom_components/myskoda/icons.json
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#268 Change range to work with all car types, make icon car-type dependant
  custom_components/myskoda/icons.json
  custom_components/myskoda/sensor.py
Labels: bugfix

#267 Add range sensors and fuel level for ICE cars
  custom_components/myskoda/icons.json
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#271 Improve processing of remaining time to charge
  custom_components/myskoda/coordinator.py
Labels: enhancement

#266 Add Honk and Flash button
  custom_components/myskoda/__init__.py
  custom_components/myskoda/button.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/manifest.json
  custom_components/myskoda/translations/en.json
  poetry.lock
  pyproject.toml
Labels: enhancement

#278 Handle new errors observed
  custom_components/myskoda/__init__.py
Labels: bugfix

#221 Implementation of door lock for supporting models
  custom_components/myskoda/__init__.py
  custom_components/myskoda/config_flow.py
  custom_components/myskoda/const.py
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/lock.py
  custom_components/myskoda/translations/en.json
  pyproject.toml
Labels: enhancement

#284 Add available vehicle and composite image URLs
  custom_components/myskoda/entity.py
  custom_components/myskoda/image.py
Labels: enhancement

#296 Improve user notifications for new Terms and Conditions
  custom_components/myskoda/__init__.py
  custom_components/myskoda/issues.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#289 update position whenever departure event is published to MQTT
  custom_components/myskoda/coordinator.py
Labels: enhancement

#319 Introduce readonly mode
  README.md
  custom_components/myskoda/button.py
  custom_components/myskoda/climate.py
  custom_components/myskoda/config_flow.py
  custom_components/myskoda/const.py
  custom_components/myskoda/number.py
  custom_components/myskoda/switch.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#350 Fix climate feature error.
  custom_components/myskoda/climate.py
Labels: bugfix

#357 AC changed to use only AIR_CONDITIONING capability
  custom_components/myskoda/climate.py
Labels: bugfix

#355 add AC settings switches
  README.md
  custom_components/myskoda/icons.json
  custom_components/myskoda/switch.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#358 Disable packaging via poetry.
  pyproject.toml
Labels: dependencies

#331 Improve error handling
  custom_components/myskoda/__init__.py
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/error_handlers.py
  custom_components/myskoda/issues.py
  custom_components/myskoda/translations/en.json
Labels: bugfix

#369 Change ChargeLimit to EntityCategory.CONFIG
  custom_components/myskoda/number.py
Labels: bugfix
