Repository skodaconnect/homeassistant-myskoda, pull requests merged in 2025-08, with the labels that each got.

#863 fix: align sensor type of battery-protection with sensor values
  custom_components/myskoda/binary_sensor.py
Labels: bugfix

#856 fix: rename unique_id of binary sensor locks from 'locked' to 'lock'
  custom_components/myskoda/__init__.py
  custom_components/myskoda/binary_sensor.py
  custom_components/myskoda/config_flow.py
  custom_components/myskoda/translations/cs.json
  custom_components/myskoda/translations/da.json
  custom_components/myskoda/translations/de.json
  custom_components/myskoda/translations/en.json
  custom_components/myskoda/translations/fi.json
  custom_components/myskoda/translations/fr.json
  custom_components/myskoda/translations/hu.json
  custom_components/myskoda/translations/it.json
  custom_components/myskoda/translations/nl.json
  custom_components/myskoda/translations/no.json
  custom_components/myskoda/translations/pl.json
  custom_components/myskoda/translations/pt-BR.json
  custom_components/myskoda/translations/pt.json
  custom_components/myskoda/translations/ro.json
  custom_components/myskoda/translations/ru.json
  custom_components/myskoda/translations/sk.json
  custom_components/myskoda/translations/sl.json
  custom_components/myskoda/translations/sv.json
Labels: maintenance

#879 Ignore dependabot changes in release notes
  .github/dependabot.yml
Labels: chore

#878 Change the criteria for charge limit number entity
  custom_components/myskoda/number.py
Labels: bugfix

#881 Let battery percentages max out at 100%
  custom_components/myskoda/device_tracker.py
  custom_components/myskoda/sensor.py
Labels: bugfix
