Repository skodaconnect/homeassistant-myskoda, pull requests merged in 2025-05, with the labels that each got.

#773 doc: update README, add FAQ
  README.md
  docs/design.md
  docs/entities.md
Labels: documentation

#785 chore: bump myskoda to 1.2.0
  custom_components/myskoda/manifest.json
  pyproject.toml
  uv.lock
Labels: chore

#791 chore(i10n): improve crowdin's PR style
  .github/workflows/crowdin-download.yml
Labels: chore

#793 chore(i10n): remove language list from crowdin pr
  .github/workflows/crowdin-download.yml
Labels: translations, chore

#800 chore(i10n): remove binary sensor state translations from localization
  custom_components/myskoda/translations/en.json
Labels: translations, chore

#804 docs(readme): update installation instructions
  README.md
Labels: documentation

#803 fix: refinements for readiness sensors
  custom_components/myskoda/binary_sensor.py
  custom_components/myskoda/icons.json
Labels: bugfix

#806 chore(deps): bump myskoda to v1.2.3
  custom_components/myskoda/manifest.json
  pyproject.toml
  uv.lock
Labels: chore

#807 chore: instruct hacs to download the zip not checkout the repo
  hacs.json
Labels: chore

#809 chore: add first iteration of security policy
  SECURITY.md
Labels: chore

#808 chore: add mit license for this repo
  LICENSE
Labels: chore

#810 chore: bump version to 1.25.0
  custom_components/myskoda/manifest.json
Labels: chore

#812 fix(i10n): remove beta from sensor names
  custom_components/myskoda/manifest.json
  custom_components/myskoda/translations/en.json
  custom_components/myskoda/translations/nl.json
  custom_components/myskoda/translations/pt-BR.json
  custom_components/myskoda/translations/pt.json
Labels: bugfix

#816 fix: actually initialize the GasRange entity
  custom_components/myskoda/sensor.py
Labels: bugfix

#818 chore: bump version to 1.25.2
  custom_components/myskoda/manifest.json
Labels: chore
