Repository skodaconnect/homeassistant-myskoda, pull requests merged in 2025-03, with the labels that each got.

#647 Prepare new release
  custom_components/myskoda/manifest.json
  hacs.json
  poetry.lock
  pyproject.toml
Labels: dependencies, chore

#652 Release v1.21.1 with myskoda==0.21.1
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#662 Automatically enable/disable entity on write action
  custom_components/myskoda/button.py
  custom_components/myskoda/climate.py
  custom_components/myskoda/lock.py
  custom_components/myskoda/number.py
  custom_components/myskoda/switch.py
Labels: enhancement

#659 Update charging logic to only update when engine is electric
  custom_components/myskoda/coordinator.py
Labels: bugfix

#670 Improve typing: ConfigEntry -> MySkodaConfigEntry
  custom_components/myskoda/__init__.py
  custom_components/myskoda/binary_sensor.py
  custom_components/myskoda/button.py
  custom_components/myskoda/climate.py
  custom_components/myskoda/config_flow.py
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/device_tracker.py
  custom_components/myskoda/diagnostics.py
  custom_components/myskoda/error_handlers.py
  custom_components/myskoda/image.py
  custom_components/myskoda/lock.py
  custom_components/myskoda/number.py
  custom_components/myskoda/sensor.py
  custom_components/myskoda/switch.py
Labels: chore

#681 Document enabling tracing
  README.md
Labels: documentation

#667 Update status for bronze integration quality scale
  custom_components/myskoda/quality_scale.yaml
Labels: documentation

#666 Remove voluptuous from dependencies
  poetry.lock
  pyproject.toml
Labels: chore

#682 Set version to 1.21.2
  custom_components/myskoda/manifest.json
  pyproject.toml
Labels: chore

#672 Update all relevant sensors when receiving EventCharging
  custom_components/myskoda/climate.py
  custom_components/myskoda/config_flow.py
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/entity.py
Labels: bugfix

#661 Remove fixtures button
  README.md
  custom_components/myskoda/__init__.py
  custom_components/myskoda/button.py
  custom_components/myskoda/config_flow.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/translations/cs.json
  custom_components/myskoda/translations/de.json
  custom_components/myskoda/translations/en.json
  custom_components/myskoda/translations/fi.json
  custom_components/myskoda/translations/fr.json
  custom_components/myskoda/translations/hu.json
  custom_components/myskoda/translations/it.json
  custom_components/myskoda/translations/nl.json
  custom_components/myskoda/translations/no.json
  custom_components/myskoda/translations/pl.json
  custom_components/myskoda/translations/pt-BR.json
  custom_components/myskoda/translations/pt.json
  custom_components/myskoda/translations/ro.json
  custom_components/myskoda/translations/ru.json
  custom_components/myskoda/translations/sk.json
  custom_components/myskoda/translations/sl.json
  custom_components/myskoda/translations/sv.json
Labels: breaking

#688 Hotfix for circular imports
  custom_components/myskoda/error_handlers.py
Labels: bugfix

#689 Fix dependencies for sensors
  custom_components/myskoda/sensor.py
Labels: bugfix

#695 Swap source for mileage sensor, health endpoint is now cached
  custom_components/myskoda/sensor.py
Labels: bugfix

#698 Set version to 1.21.3
  custom_components/myskoda/manifest.json
  pyproject.toml
Labels: chore

#708 Set version to 1.21.5
  custom_components/myskoda/manifest.json
  pyproject.toml
Labels: chore

#709 Documentation updates for push/pull and HACS install
  README.md
Labels: documentation

#712 Adjust categories of releaser
  .github/release.yml
Labels: maintenance, ignore-for-release

#713 Bump myskoda to 0.22.0
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#714 Update de.json
  custom_components/myskoda/translations/de.json
Labels: translations

#719 Bump myskoda to 0.22.1
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#716 Implement sensor indicating time left until AC has reached target
  README.md
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#722 Set version to 1.22.0
  custom_components/myskoda/manifest.json
  pyproject.toml
Labels: chore

#725 Replace config field names with their constants
  custom_components/myskoda/__init__.py
Labels: chore

#728 Add time left sensor for auxiliary heater
  custom_components/myskoda/icons.json
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#727 Tell user S-PIN is missing when operating a lock
  custom_components/myskoda/lock.py
  custom_components/myskoda/translations/en.json
Labels: bugfix

#732 Minor tweaks to issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: maintenance, ignore-for-release
