Repository skodaconnect/homeassistant-myskoda, pull requests merged in 2025-02, with the labels that each got.

#600 Improve config flow error
  custom_components/myskoda/config_flow.py
  custom_components/myskoda/translations/en.json
Labels: chore

#607 Bump myskoda to 0.19.0
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#610 fix unknown states from _on_charging_event
  custom_components/myskoda/coordinator.py
Labels: bug

#613 Bump version to 1.19.4
  custom_components/myskoda/manifest.json
  pyproject.toml
Labels: chore

#620 Bump myskoda to 0.20.0
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#624 Implement reauthentication flow
  custom_components/myskoda/config_flow.py
  custom_components/myskoda/const.py
  custom_components/myskoda/quality_scale.yaml
  custom_components/myskoda/translations/en.json
Labels: enhancement

#614 Implement user endpoint cache of 6 hours
  custom_components/myskoda/const.py
  custom_components/myskoda/coordinator.py
Labels: chore

#629 Fix update failing when user endpoint cached
  custom_components/myskoda/coordinator.py
Labels: bugfix

#630 Prepare release v1.20.0
  custom_components/myskoda/manifest.json
  pyproject.toml
Labels: chore
