Repository skodaconnect/homeassistant-myskoda, pull requests merged in 2025-01, with the labels that each got.

#447 Add seperate setup flow to coordinator
  custom_components/myskoda/coordinator.py
Labels: bugfix

#517 workaround for unavailable sensors
  custom_components/myskoda/sensor.py
Labels: bugfix

#523 fix sunroof sensor not being created
  custom_components/myskoda/binary_sensor.py
Labels: bugfix

#525 fix boot sequence
  custom_components/myskoda/coordinator.py
Labels: bugfix

#506 Implement service event sensor with history
  custom_components/myskoda/const.py
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/entity.py
  custom_components/myskoda/icons.json
  custom_components/myskoda/sensor.py
  custom_components/myskoda/translations/en.json
Labels: enhancement

#531 Fix CI by using snap install of Just
  .github/workflows/lint.yaml
Labels: dependencies

#534 Remove battery deviceclass from TargetBatteryPercentage
  custom_components/myskoda/sensor.py
Labels: bugfix

#537 Update de.json
  custom_components/myskoda/translations/de.json
Labels: translations

#538 Bump myskoda to 0.17.0
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#549 Bump myskoda to 0.17.1
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#554 Handle ClientResponseError during integration config flow
  custom_components/myskoda/config_flow.py
Labels: bugfix

#553 Update categories for changelog generator
  .github/release.yml
Labels: chore

#552 Bump minimal homeassistant to from 2024.10 to 2025.1.0
  custom_components/myskoda/entity.py
  custom_components/myskoda/number.py
  hacs.json
  poetry.lock
  pyproject.toml
Labels: dependencies

#562 Bump myskoda to 0.17.2
  custom_components/myskoda/manifest.json
  custom_components/myskoda/switch.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#568 Prepare release of 1.19.0
  custom_components/myskoda/manifest.json
  pyproject.toml
Labels: chore

#571 Fix bug in migration causing a KeyError upon initialisation
  custom_components/myskoda/__init__.py
Labels: bugfix

#555 Update README with configuration and diagnostics sensors
  README.md
Labels: documentation

#577 Fix slovak and czech translation
  custom_components/myskoda/translations/cs.json
  custom_components/myskoda/translations/sk.json
Labels: translations

#585 Add automatic version update to release process
  .github/workflows/release.yml
  custom_components/myskoda/const.py
Labels: chore

#590 Fix typo in releaser
  .github/workflows/release.yml
Labels: chore

#591 Fix another releaser typo
  .github/workflows/release.yml
Labels: chore

#592 Revert "Fix another releaser typo (#591)"
  .github/workflows/release.yml
Labels: chore

#593 Revert "Fix typo in releaser"
  .github/workflows/release.yml
Labels: chore

#594 Revert "Add automatic version update to release process"
  .github/workflows/release.yml
  custom_components/myskoda/const.py
Labels: chore

#595 Bump myskoda to 0.18.1 / prepare 1.19.2 release
  custom_components/myskoda/coordinator.py
  custom_components/myskoda/manifest.json
  poetry.lock
  pyproject.toml
Labels: dependencies
